# This job checks for broken links in various files in the repo.

name: "🔗 Broken Links"

on:
  workflow_dispatch: # Or manually dispatch the job
  push:
    branches:
      master
      
jobs:
  repo:
    name: Repo
    runs-on: [plutus-shared, self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Run Linkchecker
        run: |
          nix develop --no-warn-dirty --accept-flake-config --command ./scripts/check-broken-links.sh

  docusaurus:
    name: Docusaurus
    runs-on: [plutus-shared, self-hosted]
    steps:
      - name: Check Broken Links
        uses: ./.github/actions/linkchecker
        with: 
          url: https://plutus.cardano.intersectmbo.org/docs
          ignore-urls: |
            "https://plutus.cardano.intersectmbo.org/haddock/.*"

  metatheory:
    name: Metatheory
    runs-on: [plutus-shared, self-hosted]
    steps:
      - name: Check Broken Links
        uses: ./.github/actions/linkchecker
        with: 
          url: https://plutus.cardano.intersectmbo.org/metatheory
  
  haddock:
    name: Haddock
    runs-on: [plutus-shared, self-hosted]
    steps:
      - name: Check Broken Links
        uses: ./.github/actions/linkchecker
        with: 
          url: https://plutus.cardano.intersectmbo.org/haddock/latest
          ignore-urls: |
            "file:///run/github-runner/plutus-shared/.local/state/cabal/store/.*"
            "https://hackage.haskell.org/package/base-4.18.2.1/docs/Data-Semigroup-Internal.html"
            "https://hackage.haskell.org/package/ghc-9.6.5/docs/-/issues/7100"
            "https://hackage.haskell.org/package/ghc-boot-th-9.6.5/docs/GHC-ForeignSrcLang-Type.html"
            "https://hackage.haskell.org/package/ghc-boot-th-9.6.5/docs/GHC-LanguageExtensions-Type.html"
            "https://hackage.haskell.org/package/ghc-boot-th-9.6.5/docs/src/GHC.LanguageExtensions.Type.html"
            ".*/plutus-core/\.\.\."
            ".*/plutus-core/AlwaysInline"
            ".*/plutus-core/Barbies-Generics-Traversable.html"
            ".*/plutus-core/Barbies-Internal-Containers.html"
            ".*/plutus-core/Barbies-Internal-Trivial.html"
            ".*/plutus-core/Basement-Bits.html"
            ".*/plutus-core/Basement-Nat.html"
            ".*/plutus-core/Basement-Numerical-Subtractive.html"
            ".*/plutus-core/Basement-PrimType.html"
            ".*/plutus-core/Basement-String-Encoding-ASCII7.html"
            ".*/plutus-core/Basement-String-Encoding-ISO_8859_1.html"
            ".*/plutus-core/Basement-String-Encoding-UTF16.html"
            ".*/plutus-core/Basement-String-Encoding-UTF32.html"
            ".*/plutus-core/Cardano-Crypto-DSIGN-Class.html"
            ".*/plutus-core/Cardano-Crypto-DSIGN-EcdsaSecp256k1.html"
            ".*/plutus-core/Cardano-Crypto-DSIGN-Ed25519.html"
            ".*/plutus-core/Cardano-Crypto-DSIGN-SchnorrSecp256k1.html"
            ".*/plutus-core/Cardano-Crypto-Hash-Class.html"
            ".*/plutus-core/Cardano-Crypto-PackedBytes.html"
            ".*/plutus-core/Cardano-Crypto-PinnedSizedBytes.html"
            ".*/plutus-core/Cek-Internal.html"
            ".*/plutus-core/Codec-CBOR-Read.html"
            ".*/plutus-core/Codec-Serialise-Class.html"
            ".*/plutus-core/Control-Applicative-Backwards.html"
            ".*/plutus-core/Control-Applicative-Lift.html"
            ".*/plutus-core/Control-Comonad-Cofree.html"
            ".*/plutus-core/Control-Comonad-Trans-Cofree.html"
            ".*/plutus-core/Control-Composition.html"
            ".*/plutus-core/Control-Lens-At.html"
            ".*/plutus-core/Control-Lens-Cons.html"
            ".*/plutus-core/Control-Lens-Each.html"
            ".*/plutus-core/Control-Lens-Internal-Exception.html"
            ".*/plutus-core/Control-Lens-Internal-Indexed.html"
            ".*/plutus-core/Control-Lens-Internal-Iso.html"
            ".*/plutus-core/Control-Lens-Internal-Prism.html"
            ".*/plutus-core/Control-Lens-Plated.html"
            ".*/plutus-core/Control-Lens-Reified.html"
            ".*/plutus-core/Control-Lens-Wrapped.html"
            ".*/plutus-core/Control-Lens-Zoom.html"
            ".*/plutus-core/Control-Monad-Free-Class.html"
            ".*/plutus-core/Control-Monad-Free.html"
            ".*/plutus-core/Control-Monad-Primitive.html"
            ".*/plutus-core/Control-Monad-Trans-Accum.html"
            ".*/plutus-core/Control-Monad-Trans-Cont.html"
            ".*/plutus-core/Control-Monad-Trans-Except.html"
            ".*/plutus-core/Control-Monad-Trans-Free.html"
            ".*/plutus-core/Control-Monad-Trans-Identity.html"
            ".*/plutus-core/Control-Monad-Trans-Maybe.html"
            ".*/plutus-core/Control-Monad-Trans-RWS-CPS.html"
            ".*/plutus-core/Control-Monad-Trans-RWS-Lazy.html"
            ".*/plutus-core/Control-Monad-Trans-RWS-Strict.html"
            ".*/plutus-core/Control-Monad-Trans-Reader.html"
            ".*/plutus-core/Control-Monad-Trans-Resource-Internal.html"
            ".*/plutus-core/Control-Monad-Trans-Select.html"
            ".*/plutus-core/Control-Monad-Trans-State-Lazy.html"
            ".*/plutus-core/Control-Monad-Trans-State-Strict.html"
            ".*/plutus-core/Control-Monad-Trans-Writer-CPS.html"
            ".*/plutus-core/Control-Monad-Trans-Writer-Lazy.html"
            ".*/plutus-core/Control-Monad-Trans-Writer-Strict.html"
            ".*/plutus-core/Control-Search.html"
            ".*/plutus-core/CostModelGeneration.html"
            ".*/plutus-core/Crypto-ECC-Ed25519Donna.html"
            ".*/plutus-core/Crypto-Error-Types.html"
            ".*/plutus-core/Crypto-Hash-Types.html"
            ".*/plutus-core/Data-Aeson-Key.html"
            ".*/plutus-core/Data-Aeson-KeyMap.html"
            ".*/plutus-core/Data-Aeson-Types-FromJSON.html"
            ".*/plutus-core/Data-Aeson-Types-Internal.html"
            ".*/plutus-core/Data-Aeson-Types-ToJSON.html"
            ".*/plutus-core/Data-Attoparsec-Internal-Types.html"
            ".*/plutus-core/Data-Bifunctor-Biff.html"
            ".*/plutus-core/Data-Bifunctor-Clown.html"
            ".*/plutus-core/Data-Bifunctor-Fix.html"
            ".*/plutus-core/Data-Bifunctor-Flip.html"
            ".*/plutus-core/Data-Bifunctor-Join.html"
            ".*/plutus-core/Data-Bifunctor-Joker.html"
            ".*/plutus-core/Data-Bifunctor-Product.html"
            ".*/plutus-core/Data-Bifunctor-Sum.html"
            ".*/plutus-core/Data-Bifunctor-Tannen.html"
            ".*/plutus-core/Data-Bifunctor-Wrapped.html"
            ".*/plutus-core/Data-Bimap.html"
            ".*/plutus-core/Data-ByteString-Convert.html"
            ".*/plutus-core/Data-ByteString-Internal-Type.html"
            ".*/plutus-core/Data-ByteString-Lazy-Internal.html"
            ".*/plutus-core/Data-ByteString-Short-Internal.html"
            ".*/plutus-core/Data-Csv-Conversion.html"
            ".*/plutus-core/Data-DList-DNonEmpty-Internal.html"
            ".*/plutus-core/Data-DList-Internal.html"
            ".*/plutus-core/Data-Default-Class.html"
            ".*/plutus-core/Data-Dependent-Sum.html"
            ".*/plutus-core/Data-Fix.html"
            ".*/plutus-core/Data-Functor-Base.html"
            ".*/plutus-core/Data-Functor-Constant.html"
            ".*/plutus-core/Data-Functor-Foldable.html"
            ".*/plutus-core/Data-Functor-Reverse.html"
            ".*/plutus-core/Data-Functor-These.html"
            ".*/plutus-core/Data-Functor-Yoneda.html"
            ".*/plutus-core/Data-GADT-DeepSeq.html"
            ".*/plutus-core/Data-GADT-Internal.html"
            ".*/plutus-core/Data-HashMap-Internal-Array.html"
            ".*/plutus-core/Data-HashMap-Internal.html"
            ".*/plutus-core/Data-HashMap-Monoidal.html"
            ".*/plutus-core/Data-HashSet-Internal.html"
            ".*/plutus-core/Data-Hashable-Class.html"
            ".*/plutus-core/Data-IntMap-Internal.html"
            ".*/plutus-core/Data-IntSet-Internal.html"
            ".*/plutus-core/Data-Map-Internal.html"
            ".*/plutus-core/Data-MonoTraversable.html"
            ".*/plutus-core/Data-MultiSet.html"
            ".*/plutus-core/Data-Primitive-Array.html"
            ".*/plutus-core/Data-Primitive-PrimArray.html"
            ".*/plutus-core/Data-Primitive-SmallArray.html"
            ".*/plutus-core/Data-Primitive-Types.html"
            ".*/plutus-core/Data-Profunctor-Choice.html"
            ".*/plutus-core/Data-Profunctor-Closed.html"
            ".*/plutus-core/Data-Profunctor-Composition.html"
            ".*/plutus-core/Data-Profunctor-Mapping.html"
            ".*/plutus-core/Data-Profunctor-Strong.html"
            ".*/plutus-core/Data-Profunctor-Types.html"
            ".*/plutus-core/Data-Profunctor-Unsafe.html"
            ".*/plutus-core/Data-RAList-Tree-Internal.html"
            ".*/plutus-core/Data-Reflection.html"
            ".*/plutus-core/Data-Scientific.html"
            ".*/plutus-core/Data-Semigroup-Traversable-Class.html"
            ".*/plutus-core/Data-Sequence-Internal.html"
            ".*/plutus-core/Data-Sequences.html"
            ".*/plutus-core/Data-Set-Internal.html"
            ".*/plutus-core/Data-Some-GADT.html"
            ".*/plutus-core/Data-Some-Newtype.html"
            ".*/plutus-core/Data-Stream.html"
            ".*/plutus-core/Data-Strict-Either.html"
            ".*/plutus-core/Data-Strict-Maybe.html"
            ".*/plutus-core/Data-Strict-These.html"
            ".*/plutus-core/Data-Strict-Tuple.html"
            ".*/plutus-core/Data-Tagged.html"
            ".*/plutus-core/Data-Text-Encoding-Error.html"
            ".*/plutus-core/Data-Text-Short-Internal.html"
            ".*/plutus-core/Data-These.html"
            ".*/plutus-core/Data-Time-Calendar-Days.html"
            ".*/plutus-core/Data-Time-Clock-Internal-DiffTime.html"
            ".*/plutus-core/Data-Time-Clock-Internal-NominalDiffTime.html"
            ".*/plutus-core/Data-Time-Clock-Internal-UTCTime.html"
            ".*/plutus-core/Data-Time-Clock-Internal-UniversalTime.html"
            ".*/plutus-core/Data-Time-LocalTime-Internal-LocalTime.html"
            ".*/plutus-core/Data-Time-LocalTime-Internal-ZonedTime.html"
            ".*/plutus-core/Data-Tree.html"
            ".*/plutus-core/Data-Tuple-Only.html"
            ".*/plutus-core/Data-UUID-Types-Internal-Builder.html"
            ".*/plutus-core/Data-UUID-Types-Internal.html"
            ".*/plutus-core/Data-Vector-Primitive.html"
            ".*/plutus-core/Data-Vector-Storable.html"
            ".*/plutus-core/Data-Vector-Unboxed-Base.html"
            ".*/plutus-core/Data-Vector.html"
            ".*/plutus-core/Data.html"
            ".*/plutus-core/Flat-Decoder-Types.html"
            ".*/plutus-core/Flat-Filler.html"
            ".*/plutus-core/GHC-Exts-Heap-ClosureTypes.html"
            ".*/plutus-core/GHC-Exts-Heap-Closures.html"
            ".*/plutus-core/GHC-Exts-Heap-InfoTable-Types.html"
            ".*/plutus-core/GHC-Exts-Heap-ProfInfo-Types.html"
            ".*/plutus-core/Hedgehog-Internal-Gen.html"
            ".*/plutus-core/Hedgehog-Internal-Property.html"
            ".*/plutus-core/Hedgehog-Internal-Tree.html"
            ".*/plutus-core/Inline-CallSiteInline.html"
            ".*/plutus-core/Language-Haskell-TH-Datatype.html"
            ".*/plutus-core/Lens-Micro-Internal.html"
            ".*/plutus-core/ListT.html"
            ".*/plutus-core/N"
            ".*/plutus-core/Network-URI.html"
            ".*/plutus-core/NoThunks-Class.html"
            ".*/plutus-core/Numeric-Half-Internal.html"
            ".*/plutus-core/PLC.html"
            ".*/plutus-core/PlutusLedgerApi-Common-SerialisedScript.html"
            ".*/plutus-core/Prettyprinter-Internal.html"
            ".*/plutus-core/Prismatically.html"
            ".*/plutus-core/System-Console-Terminal-Common.html"
            ".*/plutus-core/System-OsString-Internal-Types-Hidden.html"
            ".*/plutus-core/System-Random-Internal.html"
            ".*/plutus-core/System-Random-Stateful.html"
            ".*/plutus-core/Test-QuickCheck-Arbitrary.html"
            ".*/plutus-core/Test-QuickCheck-Function.html"
            ".*/plutus-core/Test-QuickCheck-Gen.html"
            ".*/plutus-core/Test-QuickCheck-GenT-Private.html"
            ".*/plutus-core/Test-QuickCheck-GenT.html"
            ".*/plutus-core/Test-QuickCheck-Modifiers.html"
            ".*/plutus-core/Test-QuickCheck-Property.html"
            ".*/plutus-core/Text-Megaparsec-Error.html"
            ".*/plutus-core/Text-Megaparsec-Internal.html"
            ".*/plutus-core/Text-Megaparsec-Pos.html"
            ".*/plutus-core/Text-Megaparsec-State.html"
            ".*/plutus-core/Text-PrettyPrint-Annotated-WL.html"
            ".*/plutus-core/Utils.html"
            ".*/plutus-core/WithIndex.html"
            ".*/plutus-core/Witherable.html"
            ".*/plutus-core/a_non_-"
            ".*/plutus-core/folder"
            ".*/plutus-core/input"
            ".*/plutus-core/just_case_body"
            ".*/plutus-core/name"
            ".*/plutus-core/nothing_case_body"
            ".*/plutus-ghc-stub/="
            ".*/plutus-ledger-api/Alonzo.html"
            ".*/plutus-ledger-api/Control-Lens-Wrapped.html"
            ".*/plutus-ledger-api/Control-Monad-Error-Class.html"
            ".*/plutus-ledger-api/Control-Monad-Free.html"
            ".*/plutus-ledger-api/Control-Monad-Trans-Free.html"
            ".*/plutus-ledger-api/Control-Monad-Trans-Resource-Internal.html"
            ".*/plutus-ledger-api/Crypto.html"
            ".*/plutus-ledger-api/Data-Aeson-Types-FromJSON.html"
            ".*/plutus-ledger-api/Data-Aeson-Types-ToJSON.html"
            ".*/plutus-ledger-api/Data-Functor-Rep.html"
            ".*/plutus-ledger-api/Data-Profunctor-Choice.html"
            ".*/plutus-ledger-api/Data-Profunctor-Rep.html"
            ".*/plutus-ledger-api/Data-Profunctor-Unsafe.html"
            ".*/plutus-ledger-api/Data-Semigroup-Traversable-Class.html"
            ".*/plutus-ledger-api/Data-Tagged.html"
            ".*/plutus-ledger-api/Data-Time-Clock-POSIX.html"
            ".*/plutus-ledger-api/GHC.html"
            ".*/plutus-ledger-api/Hedgehog-Internal-Gen.html"
            ".*/plutus-ledger-api/Hedgehog-Internal-Property.html"
            ".*/plutus-ledger-api/Hedgehog-Internal-Tree.html"
            ".*/plutus-ledger-api/ListT.html"
            ".*/plutus-ledger-api/Prettyprinter-Internal.html"
            ".*/plutus-tx-plugin/level"
            ".*/plutus-tx/-"
            ".*/plutus-tx/Algebra-Graph-Class.html"
            ".*/plutus-tx/Basement-Bits.html"
            ".*/plutus-tx/Basement-Monad.html"
            ".*/plutus-tx/Basement-Numerical-Subtractive.html"
            ".*/plutus-tx/Codec-Serialise-Class.html"
            ".*/plutus-tx/Comment.html"
            ".*/plutus-tx/Control-Lens-At.html"
            ".*/plutus-tx/Control-Lens-Each.html"
            ".*/plutus-tx/Control-Lens-Empty.html"
            ".*/plutus-tx/Control-Monad-Error-Class.html"
            ".*/plutus-tx/Control-Monad-Trans-Control.html"
            ".*/plutus-tx/Data-Aeson-Types-FromJSON.html"
            ".*/plutus-tx/Data-Aeson-Types-ToJSON.html"
            ".*/plutus-tx/Data-Default-Class.html"
            ".*/plutus-tx/Data-Functor-Foldable.html"
            ".*/plutus-tx/Data-Hashable-Class.html"
            ".*/plutus-tx/Data-Map-Lazy.html"
            ".*/plutus-tx/Data-MonoTraversable.html"
            ".*/plutus-tx/Data-Reflection.html"
            ".*/plutus-tx/Data-Semigroup-Traversable-Class.html"
            ".*/plutus-tx/Data-Vector-Unboxed-Base.html"
            ".*/plutus-tx/Data.html"
            ".*/plutus-tx/Description.html"
            ".*/plutus-tx/GHC.html"
            ".*/plutus-tx/Lens-Micro-Internal.html"
            ".*/plutus-tx/P.html"
            ".*/plutus-tx/PlutusTx-AssocMap-Map.html"
            ".*/plutus-tx/Prettyprinter-Internal.html"
            ".*/plutus-tx/Safe.html"
            ".*/plutus-tx/System-Random-Internal.html"
            ".*/plutus-tx/Text-PrettyPrint-Annotated-WL.html"
            ".*/plutus-tx/Title.html"
            ".*/plutus-tx/Unrolling.html"
            ".*/plutus-tx/WithIndex.html"
            ".*/prettyprinter-configurable/Prettyprinter.html"
            ".*/plutus-core/src"
            ".*/plutus-tx/src"
            ".*/prettyprinter-configurable/src"


          